apiVersion: v1
kind: Pod
metadata:
  name: mypod
  labels:
    tier: frontend
spec:
  containers:
  - image: sirrikky/voice-chat:latest
    name: voice-chat
    ports:
    - containerPort: 8080
  dnsPolicy: ClusterFirst
  restartPolicy: Always